# Generated by Django 5.2.7 on 2025-11-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babytracker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babyactivity',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='babyactivity',
            name='notes',
        ),
        migrations.AddField(
            model_name='babyactivity',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='babyactivity',
            name='activity_type',
            field=models.CharField(choices=[('feeding', 'Feeding'), ('sleep', 'Sleep'), ('diaper', 'Diaper Change'), ('milestone', 'Milestone'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='babyactivity',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
