# Generated by Django 5.2.7 on 2025-11-26 20:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('babytracker', '0002_remove_babyactivity_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='babyactivity',
            old_name='time',
            new_name='timestamp',
        ),
        migrations.AddField(
            model_name='babyactivity',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='babyactivity',
            name='activity_type',
            field=models.CharField(choices=[('feeding', 'Feeding'), ('sleep', 'Sleep'), ('diaper', 'Diaper Change'), ('milestone', 'Milestone'), ('other', 'Other')], max_length=50),
        ),
    ]
